import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

class HabitIcons {
  const HabitIcons._();

  static const defaultIcon = 'sparkles';

  static const Map<String, List<String>> categories = {
    'Fitness': [
      'dumbbell', 'bike', 'footprints', 'activity', 'heartPulse',
      'mountain', 'waves', 'timer', 'trophy', 'medal', 'award', 'flame',
      'zap', 'stretch', 'flag', 'mountainSnow', 'personStanding',
      'bicepsFlexed', 'volleyball', 'goal', 'weight', 'gauge', 'bone',
      'rabbit', 'turtle', 'shield', 'swords', 'tickets', 'trendingUp',
      'circleDot', 'hand', 'accessibility',
    ],
    'Study': [
      'book', 'bookOpen', 'graduationCap', 'pencil', 'pen', 'ruler',
      'calculator', 'microscope', 'brain', 'lightbulb', 'notebookPen',
      'library', 'languages', 'compass', 'telescope', 'atom', 'backpack',
      'bookMarked', 'highlighter', 'notebook', 'scroll', 'presentation',
      'flaskConical', 'dna', 'sigma', 'binary', 'puzzle', 'penLine',
      'bookText', 'squareSigma', 'school', 'notepadText',
    ],
    'Home': [
      'house', 'bed', 'bath', 'lamp', 'utensils', 'coffee', 'key', 'hammer',
      'wrench', 'trash', 'recycle', 'shirt', 'plug', 'sofa', 'armchair',
      'refrigerator', 'microwave', 'washingMachine', 'sprayCan', 'doorOpen',
      'blinds', 'cookingPot', 'showerHead', 'paintRoller', 'toyBrick',
      'cat', 'dog', 'lampDesk',
    ],
    'Mind': [
      'heart', 'smile', 'sun', 'moon', 'star', 'cloud', 'wind', 'leaf',
      'sparkles', 'flame', 'snowflake', 'music', 'sunrise', 'sunset',
      'laugh', 'smilePlus', 'feather', 'infinity', 'orbit', 'rainbow',
      'cloudMoon', 'handHeart', 'quote', 'notebookText', 'angry', 'frown',
      'meh', 'eclipse', 'moonStar',
    ],
    'Food': [
      'apple', 'salad', 'glassWater', 'droplet', 'coffee', 'pill', 'egg',
      'fish', 'carrot', 'cookie', 'utensils', 'wine', 'banana', 'beef',
      'cake', 'candy', 'cherry', 'citrus', 'croissant', 'cupSoda',
      'dessert', 'drumstick', 'grape', 'iceCreamCone', 'milk', 'nut',
      'pizza', 'popcorn', 'sandwich', 'soup', 'wheat', 'martini', 'beer',
      'ham', 'popsicle', 'vegan', 'bean',
    ],
    'Work': [
      'briefcase', 'target', 'clock', 'calendarDays', 'mail', 'phone',
      'presentation', 'clipboardCheck', 'inbox', 'rocket', 'code',
      'chartBar', 'badge', 'building', 'building2', 'printer', 'folder',
      'folderOpen', 'fileText', 'paperclip', 'calendarCheck', 'listTodo',
      'listChecks', 'notebookTabs', 'alarmClock', 'hourglass', 'userCheck',
      'chartPie', 'chartLine', 'handCoins',
    ],
    'Social': [
      'users', 'handshake', 'messageCircle', 'gift', 'phone', 'mail',
      'heartHandshake', 'partyPopper', 'smile', 'userPlus', 'usersRound',
      'messageSquare', 'send', 'share2', 'phoneCall', 'video', 'ticket',
      'mapPin', 'calendarHeart', 'contact', 'baby', 'userRound',
      'megaphone', 'bellRing',
    ],
    'Finance': [
      'dollar', 'piggyBank', 'trendingUp', 'coins', 'creditCard', 'wallet',
      'banknote', 'receipt', 'landmark', 'percent',
      'circleDollarSign', 'euro', 'poundSterling', 'bitcoin', 'gem',
      'vault', 'shoppingCart', 'shoppingBag', 'tag', 'calculator',
      'chartNoAxesCombined', 'handCoins', 'badgeDollarSign',
    ],
    'Nature': [
      'trees', 'sprout', 'leaf', 'flower', 'globe', 'recycle', 'sun',
      'cloudRain', 'mountain', 'waves', 'bird', 'tent', 'treePine',
      'treePalm', 'flower2', 'snail', 'bug', 'squirrel', 'rabbit', 'fish',
      'shell', 'cloudSun', 'droplets', 'thermometer', 'map', 'mountainSnow',
      'sunrise', 'sunset', 'earth', 'feather', 'leafyGreen',
    ],
    'Tech': [
      'laptop', 'smartphone', 'headphones', 'camera', 'gamepad', 'code',
      'terminal', 'bug', 'wifi', 'keyboard', 'monitor', 'database',
      'mouse', 'server', 'cpu', 'hardDrive',
      'smartphoneCharging', 'tablet', 'tv', 'radio', 'disc', 'usb',
      'bluetooth', 'batteryCharging', 'memoryStick', 'webcam',
      'mousePointer', 'cloudUpload',
    ],
    'Art': [
      'palette', 'paintbrush', 'guitar', 'music', 'film', 'pen', 'camera',
      'mic', 'brush', 'scissors', 'image', 'paintbrushVertical',
      'paintRoller', 'piano', 'drum', 'theater', 'clapperboard', 'aperture',
      'penTool', 'pencilRuler', 'shapes', 'sticker', 'wandSparkles',
      'drama', 'audioLines', 'frame', 'highlighter',
    ],
  };

  static const Map<String, IconData> all = {
    'dumbbell': LucideIcons.dumbbell,
    'bike': LucideIcons.bike,
    'footprints': LucideIcons.footprints,
    'activity': LucideIcons.activity,
    'heartPulse': LucideIcons.heartPulse,
    'mountain': LucideIcons.mountain,
    'waves': LucideIcons.waves,
    'timer': LucideIcons.timer,
    'trophy': LucideIcons.trophy,
    'medal': LucideIcons.medal,
    'award': LucideIcons.award,
    'flame': LucideIcons.flame,
    'zap': LucideIcons.zap,
    'stretch': LucideIcons.stretchHorizontal,
    'flag': LucideIcons.flag,
    'mountainSnow': LucideIcons.mountainSnow,
    'personStanding': LucideIcons.personStanding,
    'bicepsFlexed': LucideIcons.bicepsFlexed,
    'volleyball': LucideIcons.volleyball,
    'goal': LucideIcons.goal,
    'weight': LucideIcons.weight,
    'gauge': LucideIcons.gauge,
    'bone': LucideIcons.bone,
    'rabbit': LucideIcons.rabbit,
    'turtle': LucideIcons.turtle,
    'shield': LucideIcons.shield,
    'swords': LucideIcons.swords,
    'tickets': LucideIcons.tickets,
    'trendingUp': LucideIcons.trendingUp,
    'circleDot': LucideIcons.circleDot,
    'hand': LucideIcons.hand,
    'accessibility': LucideIcons.accessibility,
    'book': LucideIcons.book,
    'bookOpen': LucideIcons.bookOpen,
    'graduationCap': LucideIcons.graduationCap,
    'pencil': LucideIcons.pencil,
    'pen': LucideIcons.pen,
    'ruler': LucideIcons.ruler,
    'calculator': LucideIcons.calculator,
    'microscope': LucideIcons.microscope,
    'brain': LucideIcons.brain,
    'lightbulb': LucideIcons.lightbulb,
    'notebookPen': LucideIcons.notebookPen,
    'library': LucideIcons.library,
    'languages': LucideIcons.languages,
    'compass': LucideIcons.compass,
    'telescope': LucideIcons.telescope,
    'atom': LucideIcons.atom,
    'backpack': LucideIcons.backpack,
    'bookMarked': LucideIcons.bookMarked,
    'highlighter': LucideIcons.highlighter,
    'notebook': LucideIcons.notebook,
    'scroll': LucideIcons.scroll,
    'presentation': LucideIcons.presentation,
    'flaskConical': LucideIcons.flaskConical,
    'dna': LucideIcons.dna,
    'sigma': LucideIcons.sigma,
    'binary': LucideIcons.binary,
    'puzzle': LucideIcons.puzzle,
    'penLine': LucideIcons.penLine,
    'bookText': LucideIcons.bookText,
    'squareSigma': LucideIcons.squareSigma,
    'school': LucideIcons.school,
    'notepadText': LucideIcons.notepadText,
    'house': LucideIcons.house,
    'bed': LucideIcons.bed,
    'bath': LucideIcons.bath,
    'lamp': LucideIcons.lamp,
    'utensils': LucideIcons.utensils,
    'coffee': LucideIcons.coffee,
    'key': LucideIcons.key,
    'hammer': LucideIcons.hammer,
    'wrench': LucideIcons.wrench,
    'trash': LucideIcons.trash2,
    'recycle': LucideIcons.recycle,
    'shirt': LucideIcons.shirt,
    'plug': LucideIcons.plug,
    'sofa': LucideIcons.sofa,
    'armchair': LucideIcons.armchair,
    'refrigerator': LucideIcons.refrigerator,
    'microwave': LucideIcons.microwave,
    'washingMachine': LucideIcons.washingMachine,
    'sprayCan': LucideIcons.sprayCan,
    'doorOpen': LucideIcons.doorOpen,
    'blinds': LucideIcons.blinds,
    'cookingPot': LucideIcons.cookingPot,
    'showerHead': LucideIcons.showerHead,
    'paintRoller': LucideIcons.paintRoller,
    'toyBrick': LucideIcons.toyBrick,
    'cat': LucideIcons.cat,
    'dog': LucideIcons.dog,
    'lampDesk': LucideIcons.lampDesk,
    'heart': LucideIcons.heart,
    'smile': LucideIcons.smile,
    'sun': LucideIcons.sun,
    'moon': LucideIcons.moon,
    'star': LucideIcons.star,
    'cloud': LucideIcons.cloud,
    'wind': LucideIcons.wind,
    'leaf': LucideIcons.leaf,
    'sparkles': LucideIcons.sparkles,
    'snowflake': LucideIcons.snowflake,
    'music': LucideIcons.music,
    'sunrise': LucideIcons.sunrise,
    'sunset': LucideIcons.sunset,
    'laugh': LucideIcons.laugh,
    'smilePlus': LucideIcons.smilePlus,
    'feather': LucideIcons.feather,
    'infinity': LucideIcons.infinity,
    'orbit': LucideIcons.orbit,
    'rainbow': LucideIcons.rainbow,
    'cloudMoon': LucideIcons.cloudMoon,
    'handHeart': LucideIcons.handHeart,
    'quote': LucideIcons.quote,
    'notebookText': LucideIcons.notebookText,
    'angry': LucideIcons.angry,
    'frown': LucideIcons.frown,
    'meh': LucideIcons.meh,
    'eclipse': LucideIcons.eclipse,
    'moonStar': LucideIcons.moonStar,
    'apple': LucideIcons.apple,
    'salad': LucideIcons.salad,
    'glassWater': LucideIcons.glassWater,
    'droplet': LucideIcons.droplet,
    'pill': LucideIcons.pill,
    'egg': LucideIcons.egg,
    'fish': LucideIcons.fish,
    'carrot': LucideIcons.carrot,
    'cookie': LucideIcons.cookie,
    'wine': LucideIcons.wine,
    'banana': LucideIcons.banana,
    'beef': LucideIcons.beef,
    'cake': LucideIcons.cake,
    'candy': LucideIcons.candy,
    'cherry': LucideIcons.cherry,
    'citrus': LucideIcons.citrus,
    'croissant': LucideIcons.croissant,
    'cupSoda': LucideIcons.cupSoda,
    'dessert': LucideIcons.dessert,
    'drumstick': LucideIcons.drumstick,
    'grape': LucideIcons.grape,
    'iceCreamCone': LucideIcons.iceCreamCone,
    'milk': LucideIcons.milk,
    'nut': LucideIcons.nut,
    'pizza': LucideIcons.pizza,
    'popcorn': LucideIcons.popcorn,
    'sandwich': LucideIcons.sandwich,
    'soup': LucideIcons.soup,
    'wheat': LucideIcons.wheat,
    'martini': LucideIcons.martini,
    'beer': LucideIcons.beer,
    'ham': LucideIcons.ham,
    'popsicle': LucideIcons.popsicle,
    'vegan': LucideIcons.vegan,
    'bean': LucideIcons.bean,
    'briefcase': LucideIcons.briefcase,
    'target': LucideIcons.target,
    'clock': LucideIcons.clock,
    'calendarDays': LucideIcons.calendarDays,
    'mail': LucideIcons.mail,
    'phone': LucideIcons.phone,
    'clipboardCheck': LucideIcons.clipboardCheck,
    'inbox': LucideIcons.inbox,
    'rocket': LucideIcons.rocket,
    'code': LucideIcons.code,
    'chartBar': LucideIcons.chartColumn,
    'badge': LucideIcons.badge,
    'building': LucideIcons.building,
    'building2': LucideIcons.building2,
    'printer': LucideIcons.printer,
    'folder': LucideIcons.folder,
    'folderOpen': LucideIcons.folderOpen,
    'fileText': LucideIcons.fileText,
    'paperclip': LucideIcons.paperclip,
    'calendarCheck': LucideIcons.calendarCheck,
    'listTodo': LucideIcons.listTodo,
    'listChecks': LucideIcons.listChecks,
    'notebookTabs': LucideIcons.notebookTabs,
    'alarmClock': LucideIcons.alarmClock,
    'hourglass': LucideIcons.hourglass,
    'userCheck': LucideIcons.userCheck,
    'chartPie': LucideIcons.chartPie,
    'chartLine': LucideIcons.chartLine,
    'handCoins': LucideIcons.handCoins,
    'users': LucideIcons.users,
    'handshake': LucideIcons.handshake,
    'messageCircle': LucideIcons.messageCircle,
    'gift': LucideIcons.gift,
    'heartHandshake': LucideIcons.heartHandshake,
    'partyPopper': LucideIcons.partyPopper,
    'userPlus': LucideIcons.userPlus,
    'usersRound': LucideIcons.usersRound,
    'messageSquare': LucideIcons.messageSquare,
    'send': LucideIcons.send,
    'share2': LucideIcons.share2,
    'phoneCall': LucideIcons.phoneCall,
    'video': LucideIcons.video,
    'ticket': LucideIcons.ticket,
    'mapPin': LucideIcons.mapPin,
    'calendarHeart': LucideIcons.calendarHeart,
    'contact': LucideIcons.contact,
    'baby': LucideIcons.baby,
    'userRound': LucideIcons.userRound,
    'megaphone': LucideIcons.megaphone,
    'bellRing': LucideIcons.bellRing,
    'dollar': LucideIcons.dollarSign,
    'piggyBank': LucideIcons.piggyBank,
    'coins': LucideIcons.coins,
    'creditCard': LucideIcons.creditCard,
    'wallet': LucideIcons.wallet,
    'banknote': LucideIcons.banknote,
    'receipt': LucideIcons.receipt,
    'landmark': LucideIcons.landmark,
    'percent': LucideIcons.percent,
    'circleDollarSign': LucideIcons.circleDollarSign,
    'euro': LucideIcons.euro,
    'poundSterling': LucideIcons.poundSterling,
    'bitcoin': LucideIcons.bitcoin,
    'gem': LucideIcons.gem,
    'vault': LucideIcons.vault,
    'shoppingCart': LucideIcons.shoppingCart,
    'shoppingBag': LucideIcons.shoppingBag,
    'tag': LucideIcons.tag,
    'chartNoAxesCombined': LucideIcons.chartNoAxesCombined,
    'badgeDollarSign': LucideIcons.badgeDollarSign,
    'trees': LucideIcons.trees,
    'sprout': LucideIcons.sprout,
    'flower': LucideIcons.flower,
    'globe': LucideIcons.globe,
    'cloudRain': LucideIcons.cloudRain,
    'bird': LucideIcons.bird,
    'tent': LucideIcons.tent,
    'treePine': LucideIcons.treePine,
    'treePalm': LucideIcons.treePalm,
    'flower2': LucideIcons.flower2,
    'snail': LucideIcons.snail,
    'bug': LucideIcons.bug,
    'squirrel': LucideIcons.squirrel,
    'shell': LucideIcons.shell,
    'cloudSun': LucideIcons.cloudSun,
    'droplets': LucideIcons.droplets,
    'thermometer': LucideIcons.thermometer,
    'map': LucideIcons.map,
    'earth': LucideIcons.earth,
    'leafyGreen': LucideIcons.leafyGreen,
    'laptop': LucideIcons.laptop,
    'smartphone': LucideIcons.smartphone,
    'headphones': LucideIcons.headphones,
    'camera': LucideIcons.camera,
    'gamepad': LucideIcons.gamepad2,
    'terminal': LucideIcons.terminal,
    'wifi': LucideIcons.wifi,
    'keyboard': LucideIcons.keyboard,
    'monitor': LucideIcons.monitor,
    'database': LucideIcons.database,
    'mouse': LucideIcons.mouse,
    'server': LucideIcons.server,
    'cpu': LucideIcons.cpu,
    'hardDrive': LucideIcons.hardDrive,
    'smartphoneCharging': LucideIcons.smartphoneCharging,
    'tablet': LucideIcons.tablet,
    'tv': LucideIcons.tv,
    'radio': LucideIcons.radio,
    'disc': LucideIcons.disc,
    'usb': LucideIcons.usb,
    'bluetooth': LucideIcons.bluetooth,
    'batteryCharging': LucideIcons.batteryCharging,
    'memoryStick': LucideIcons.memoryStick,
    'webcam': LucideIcons.webcam,
    'mousePointer': LucideIcons.mousePointer,
    'cloudUpload': LucideIcons.cloudUpload,
    'palette': LucideIcons.palette,
    'paintbrush': LucideIcons.paintbrush,
    'guitar': LucideIcons.guitar,
    'film': LucideIcons.film,
    'mic': LucideIcons.mic,
    'brush': LucideIcons.brush,
    'scissors': LucideIcons.scissors,
    'image': LucideIcons.image,
    'paintbrushVertical': LucideIcons.paintbrushVertical,
    'piano': LucideIcons.piano,
    'drum': LucideIcons.drum,
    'theater': LucideIcons.theater,
    'clapperboard': LucideIcons.clapperboard,
    'aperture': LucideIcons.aperture,
    'penTool': LucideIcons.penTool,
    'pencilRuler': LucideIcons.pencilRuler,
    'shapes': LucideIcons.shapes,
    'sticker': LucideIcons.sticker,
    'wandSparkles': LucideIcons.wandSparkles,
    'drama': LucideIcons.drama,
    'audioLines': LucideIcons.audioLines,
    'frame': LucideIcons.frame,
  };
  static List<String> get names => all.keys.toList();

  static IconData resolve(String name) => all[name] ?? all[defaultIcon]!;

  static bool isIcon(String name) => all.containsKey(name);
}
